GO_EASY_ON_ME = 1

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = ToggleFlashVideoiOS10
ToggleFlashVideoiOS10_FILES = Tweak10.xm
ToggleFlashVideoiOS10_LIBRARIES = substrate
ToggleFlashVideoiOS10_INSTALL_PATH = /Library/Application Support/RecordNTorch

include $(THEOS_MAKE_PATH)/library.mk
