TARGET = iphone:clang:latest:9.0

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = ToggleFlashVideoiOS910
ToggleFlashVideoiOS910_FILES = Tweak.xm
ToggleFlashVideoiOS910_LIBRARIES = substrate
ToggleFlashVideoiOS910_INSTALL_PATH = /Library/Application Support/RecordNTorch

include $(THEOS_MAKE_PATH)/library.mk
