TARGET = iphone:clang:8.1:8.0

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = ToggleFlashVideoiOS8
ToggleFlashVideoiOS8_FILES = Tweak.xm
ToggleFlashVideoiOS8_EXTRA_FRAMEWORKS = CydiaSubstrate
ToggleFlashVideoiOS8_INSTALL_PATH = /Library/MobileSubstrate/DynamicLibraries/RecordNTorch

include $(THEOS_MAKE_PATH)/library.mk
