include $(THEOS)/makefiles/common.mk
	
LIBRARY_NAME = ToggleFlashVideoiOS8
ToggleFlashVideoiOS8_FILES = Tweak8.xm
ToggleFlashVideoiOS8_LIBRARIES = substrate
ToggleFlashVideoiOS8_INSTALL_PATH = /Library/Application Support/RecordNTorch

include $(THEOS_MAKE_PATH)/library.mk