include $(THEOS)/makefiles/common.mk
	
LIBRARY_NAME = ToggleFlashVideoiOS9
ToggleFlashVideoiOS9_FILES = Tweak9.xm
ToggleFlashVideoiOS9_LIBRARIES = substrate
ToggleFlashVideoiOS9_INSTALL_PATH = /Library/Application Support/RecordNTorch

include $(THEOS_MAKE_PATH)/library.mk