TARGET = iphone:clang:latest:5.0
ARCHS = armv7

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = ToggleFlashVideoiOS56
ToggleFlashVideoiOS56_FILES = Tweak.xm
ToggleFlashVideoiOS56_LIBRARIES = substrate
ToggleFlashVideoiOS56_INSTALL_PATH = /Library/Application Support/RecordNTorch

include $(THEOS_MAKE_PATH)/library.mk
