TARGET = iphone:clang:6.0:5.0
ARCHS = armv7

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = ToggleFlashVideoiOS56
ToggleFlashVideoiOS56_FILES = Tweak.xm
ToggleFlashVideoiOS56_EXTRA_FRAMEWORKS = CydiaSubstrate
ToggleFlashVideoiOS56_INSTALL_PATH = /Library/MobileSubstrate/DynamicLibraries/RecordNTorch

include $(THEOS_MAKE_PATH)/library.mk
