include $(THEOS)/makefiles/common.mk
	
LIBRARY_NAME = ToggleFlashVideoiOS7
ToggleFlashVideoiOS7_FILES = Tweak7.xm
ToggleFlashVideoiOS7_LIBRARIES = substrate
ToggleFlashVideoiOS7_INSTALL_PATH = /Library/Application Support/RecordNTorch

include $(THEOS_MAKE_PATH)/library.mk