TARGET = iphone:clang:latest:7.0

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = ToggleFlashVideoiOS7
ToggleFlashVideoiOS7_FILES = Tweak.xm
ToggleFlashVideoiOS7_LIBRARIES = substrate
ToggleFlashVideoiOS7_INSTALL_PATH = /Library/Application Support/RecordNTorch

include $(THEOS_MAKE_PATH)/library.mk
