TARGET = iphone:clang:7.1:7.0

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = ToggleFlashVideoiOS7
ToggleFlashVideoiOS7_FILES = Tweak.xm
ToggleFlashVideoiOS7_EXTRA_FRAMEWORKS = CydiaSubstrate
ToggleFlashVideoiOS7_INSTALL_PATH = /Library/MobileSubstrate/DynamicLibraries/RecordNTorch

include $(THEOS_MAKE_PATH)/library.mk
